### ISSUE TITLE
Form controls 

### ISSUE THREAD

**Issue by pgroot91** [CodyHouse/cd-wizard-form-changelog#1]
I'm unable to replicate a working version of the wizard. 
Unable to make the navigation to work. 
All buttons are shown on the first step (Back, Next and Submit).

Don't see any console errors.

![image](https://user-images.githubusercontent.com/6934501/87142298-a52f7f80-c2a4-11ea-82d8-4727efd6ed42.png)

Steps to reproduce copying the html css and js from the wizard form component only.

**Comment by imatrycode** [comment]
I am on 

> 
> 
> I'm unable to replicate a working version of the wizard.
> Unable to make the navigation to work.
> All buttons are shown on the first step (Back, Next and Submit).
> 
> Don't see any console errors.
> 
> ![image](https://user-images.githubusercontent.com/6934501/87142298-a52f7f80-c2a4-11ea-82d8-4727efd6ed42.png)
> 
> Steps to reproduce copying the html css and js from the wizard form component only.

I am having the same issue, looks like you do have to initiate this:

e.g. 

<script>
  var wizardForm = document.getElementsByClassName('js-wiz-form')[0];
  var wizardFormObj = new WizardForm(wizardForm[0]);
</script>

Which does seem to initiate the form
Added console.log("WizardForm initiated"); to the initiateWizardForm function in the provided js

however my buttons still look like yours

Ive tried looking through the script adding console log see where it gets but I must be missing something

**Comment by imatrycode** [comment]
Actually I just sorted mine.

Add this:

<script>
var wizardForm = document.getElementsByClassName('js-wiz-form');
var wizardFormObj = new WizardForm(wizardForm[0]);
</script>

Underneath

 <script src="assets/js/scripts.js"></script>

In your page, originally it had:
var wizardForm = document.getElementsByClassName('js-wiz-form')**[0]**;
var wizardFormObj = new WizardForm(wizardForm[0]);

The index looks to cause it not to initialise

**Comment by imatrycode** [comment]
so:

`</form>     
 <script src="assets/js/scripts.js"></script>
 <script>
  var wizardForm = document.getElementsByClassName('js-wiz-form');
  var wizardFormObj = new WizardForm(wizardForm[0]);
  //wizardFormObj.updateForm();
  wizardFormObj.showStep(1);
   </script>
</body>
</html>`

**Comment by pgroot91** [comment]
@imatrycode Thanks! After watching the info page we realized actually missed that. Really happy we have it working also 👍

**Comment by sebastiano-guerriero** [comment]
Great! I'm closing the issue. Let us know if you have other questions :)
