### ISSUE TITLE
Validate fields when going step forward (without submitting)

### ISSUE THREAD

**Issue by vaelu** [CodyHouse/cd-wizard-form-changelog#2]
Hello guys

It would be really cool if you could provide a solution on how to validate fields when clicking "Next" and then it should not go to the next page when something is wrong. Because without validating it does not make sense since the user can't submit the form at the end, but he does not know where the problem is.

Thanks :)

**Comment by sebastiano-guerriero** [comment]
Good point! We're working on it 👍

**Comment by claudia-romano** [comment]
We have updated the Wizard Form component to include the option to validate fields before changing step. You can get the updated JS code here:
https://codyhouse.co/ds/components/app/wizard-form

Make sure to include the new [Form Validator component](https://codyhouse.co/ds/components/app/form-validator) as well.

More info on how to set the validation on the component [Info page](https://codyhouse.co/ds/components/info/wizard-form#validate-form).
