### ISSUE TITLE
Wizard Form + Form Validator

### ISSUE THREAD

**Issue by paveell** [CodyHouse/cd-wizard-form-changelog#4]
Tell me why Form Validator is not compatible with Wizard Form?

At the first step, the validation works, but if you go to the third step and the subsequent steps, the validation script does not work. 

Thank you!

**Comment by claudia-romano** [comment]
Hi there, could you please provide more info about the bug (e.g., fields that are not working, what you mean by 'the validation script does not work', browser you are using)? 

The Wizard Form has been built to work in combo with the Form Validator; I have double checked and everything seems to be working fine. Thanks.

**Comment by claudia-romano** [comment]
Hi there, I'm closing this issue as no additional info was provided. Feel free to reopen it if you are still experiencing the problem. Cheers!
