### ISSUE TITLE
Wizard doesn't have the right height

### ISSUE THREAD

**Issue by dariopetraroia** [CodyHouse/cd-wizard-form-changelog#5]
Hy,

the wizard doesn't have the right height so the footer doesn't display correctly.

I used this page: https://codyhouse.co/app/components/demo/demo-wizard-form

Please check video

Thanks

https://user-images.githubusercontent.com/5861215/207043011-f6eb47df-ec11-496b-bbbd-ad4c806bd3c9.mp4

**Comment by claudia-romano** [comment]
Hi Dario, this is a bug of the `vh` unit on iOS. You can set the `.wiz-form` height to `100svh` (rather than `100vh`) and this should solve the issue.

**Comment by claudia-romano** [comment]
Hi Dario, the component has been updated to use the dynamic viewport units (100dvh) that fix the issue. Cheers!
